### PR TITLE
Refactor logic for dry and clean code

### PR DESCRIPTION
**Pull request by vijay991**

### CODE REVIEW

**Comment by 2KAbhishek** [comment]
Any particular reason for changing the tests file? @vijay991

**Comment by vijay991** [comment]
> Any particular reason for changing the tests file? @vijay991

Hi @2KAbhishek 
Yes, The modifications made to the test file were essential to align with the changes introduced during the refactoring of the Spacecraft class. Earlier test cases was based on single function that I have used, but after refactor the functions are more generic hence  test cases too.

**Comment by 2KAbhishek** [comment]
@vijay991 merge the pr 😁

**Comment by vijay991** [comment]
> @vijay991 merge the pr 😁

Sure, Thanks for the approval ☺️ @2KAbhishek

**Pull request merged**
